#!/bin/bash

# find a list of markdowns
# remove the extension just to get the file name
# remove personal files and others that you want to exclude

./generate_home_page > mdfiles/notes/posts.md

list_of_files=$(ls -t mdfiles/notes/ | sed -e 's/\.md$//' | grep -v 'personal')

# remove all the html files and remake the folder

rm -rf content/
mkdir -p content/

# for every md, make the conversion to html

for md in ${list_of_files[@]}; do
  echo -e "\nConverting ${md}.md..."
  pandoc -s mdfiles/notes/${md}.md -o content/${md}.html --template=assets/templates/post.html 2> /dev/null
done
