#!/bin/bash

# find a list of the markdown files
# sorting it by update time
# removing all personal files, about and index files

list_of_files=$(ls -lt mdfiles/ | awk '{print $9}' | grep -v 'posts.md\|index.md\|roadmap.md\|personal*' | sed -e 's/\.md$//')

# for every file make a list of links

echo $'---\ntitle: ayn\n---\n﷽\n'

echo $'Here are the most recent posts:\n'

for md in ${list_of_files[@]}; do
  md_title=$(grep 'title: *' mdfiles/${md}.md | awk '{$1=""; print$0}')

  echo -e "- [${md_title}](./${md}.html)"
done

# get the title's by cat-ing the output

